project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 2024 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://plnrbrt.github.io/STA9750-2024-FALL/"
  navbar:
    background: primary
    search: false
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        menu:
          - text: "Mini Project 1"
            href: mp01.qmd
          - text: "Mini Project 2"
            href: mp02.qmd
      - text: "Contact"
        href: contact.qmd  

format:
  html:
    css: styles.css  
    toc: false

