project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 2024 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://plnrbrt.github.io/STA9750-2024-FALL/"
  navbar:
    background: primary
    search: false
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd  # New contact tab

format:
  html:
    theme: quartz
    toc: false
    css: styles.css
